---
title: "**政府干预下离汉人员对新冠疫情的影响分析**"
author: 
    "虞睿灵;  董洁;  常佳琪"  
date: "2020/06/20"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
  word_document: default
CJKmainfont: Microsoft YaHei
fontsize: 12pt
geometry: "left=2.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
abstract: COVID-19疫情于2020年年初在中国大陆地区快速蔓延，为有效防控疫情，中央切断源头，对湖北武汉市进行全面封城。本文通过相关分析、互相关分析分析离汉人员的分布差异和离汉人员对其他省份疫情的影响，通过构建Arimax模型来评估武汉封城令这一政策对疫情防控的效果。结果表明，离汉人员在一定程度上对其他省份的疫情存在影响，武汉封城令这一政策干预确实有效的减少了疫情传播。
---

# 1. 引言

## 1.1 背景及研究意义

2019新型冠状病毒肺炎于2019年12月在湖北省武汉市出现，其显著的人传人特性伴随着高密度的人口流动导致病毒迅速蔓延，成为新中国成立以来在我国发生的传播速度最快、感染范围最广、防控难度最大的一次重大突发公共卫生事件。为有效防控疫情，中央采取强有力的干预政策，于2020年1月23日对武汉进行全面封城。  

由于在疫情爆发初期，中国正处于春运高峰期，受到疫情影响，大量在汉群众加快离开武汉的步伐，在一定程度上加速了其他地区的疫情发展。随着武汉封城令的实施，离汉人数出现断崖式下降，在一定程度上遏制了疫情进一步蔓延。  

在这一背景下，研究武汉封城令对新冠疫情的影响意义重大。本文旨在通过分析疫情初期离汉人员对其他30个省市自治区新冠病例的影响，来评估武汉封城这一政策干预对疫情防控的效果。  

## 1.2 文献综述

在新冠疫情爆发初期，我国各省市自治区在中央领导下多次通过政府干预对疫情进行防控。随着我国新增确诊病数量例的快速减少，各项政府干预政策受到国内外各界高度关注，部分学者也对这些政策效果进行了分析与评价。  

其中，林华珍教授团队（2020）主要运用疫情病例数据和交通运输数据建立时间序列模型，通过对数似然估计得到病例的实时潜在传输率，评估各省公共干预对新冠病例传播率的影响；方亚、石再兴教授（2020）运用arimax模型结合互相关分析，研究了交通量和疫情发病率的时间滞后关系，评估武汉封城令对新冠疫情累计发病率的影响；杨华磊等人（2020）运用SIR模型结合易感人群、感染人群以及传播介质分析人口迁徙对新冠病毒感染人数的影响；廖可等人（2020）运用格兰杰因果检验分析迁徙指数与新增病例数之间的因果关系；陈田木等人（2020）通过构建SEIAR模型拟合厦门市新冠肺炎在政府干预前后的有效再生数，评估厦门市政府综合干预的防控效果。  

## 1.3 研究思路

本文主要通过研究疫情初期离汉人员与其他30个省市自治区疫情的相关关系，评估武汉封城这一政策干预对疫情发展的影响效果。其具体研究思路如下：1.通过相关分析分析武汉迁出到各省人数差异的原因；2.运用格兰杰因果检验，分析累计确诊病例与累计迁出人数的因果关系；3.通过预白化互相关分析，研究确诊病例与迁出人数之间的滞后相关关系；4.根据互相关分析结果分类构建Arimax模型，评估武汉封城政策对疫情防控的效果。

# 2. 理论分析

## 2.1 格兰杰因果检验

Granger因果检验，最早由Granger于20世纪60年代末提出，习惯上通常被称为Granger因果关系检验。Granger因果关系检验一般用于检验两个变量之间的变动是否存在因果关系，根据变量间因果关系的影响方向不同，其结果可分为单向关系和双向关系。如果一个变量过去发生的变动影响另一个变量当前发生变化，则为单向影响关系；如果两个变量过去发生的变化都影响另外的变量现在发生变化，则二者存在双向Granger因果检验关系。Granger因果检验的完成，需要借助受约束的F检验来完成，其相关公式如下：

$$
Y_{t}=\sum_{i=1}^{m} \alpha_{i} X_{t-i}+\sum_{i=1}^{m} \beta_{i} Y_{t-i}+\mu_{i}
$$
$$
\mathrm{F}=\frac{\left(\mathrm{RSS}_{\mathrm{R}}-\mathrm{RSS}_{\mathrm{U}}\right) / m}{\operatorname{RSS}_{U} /(n-k)}
$$
$$
\mathrm{H}_{0}: \alpha_{1}=\alpha_{2}=\alpha_{3}=\mathrm{L}=\alpha_{\mathrm{m}}=0
$$
其中，当F统计量满足$\mathrm{F}<\mathrm{F}_{\alpha}(\mathrm{m}, \mathrm{n}-\mathrm{k})$时，变量X是变量Y的Granger原因。

## 2.2 互相关分析

互相关函数是描述随机信号$x_{t}$和$y_{t}$在任意两个不同时刻s,t的取值之间的相关程度，是一种非常有用的测度两个变量之间相关强度和方向的函数。  

由于总体的互相关函数是未知的，为了讨论两个时间序列的互相关函数，通常用一个跨度为n的样本来估计总体互相关函数，假设这个跨度为n的样本为$(x_1,y_1),(x_2,y_2),……(x_n,y_n)$。样本的互协方差函数为：
$$
\gamma_{xy}(k)=\left\{
\begin{aligned}
\frac 1n \sum_{t=1}^{n-k} (x_t-\overline{x})(y_{t+k}-\overline{y})       &      & k=0,1,2,...\\
\frac 1n \sum_{t=1}^{n+k} (y_t-\overline{y})(x_{t-k}-\overline{x})     &      & k=0,-1,-2,...\end{aligned}
\right.
$$
样本的互相关系数为:
$$
\hat\rho_{xy}(k)=\frac{\gamma_{xy}(k)}{S_xS_y}             
$$
然而，由于CCF受x变量的时间序列结构以及x和y序列随时间的任何“共同”趋势的影响，因此在对两时间序列做互相关分析前通常要进行预白化处理,及利用X变量过滤Y变量，消除两者的共同趋势。

## 2.3 Arimax分析

Arimax模型，是在对变量协整关系研究的基础上将时间序列分析与多元回归分析结合提出得一种模型。它是在Arima模型的基础上引入解释变量，建立了附带解释变量的Arima模型，也称扩展的Arima模型，从而提高时间序列的预测精度。Arimax模型可表示为：  
$$y_{t} = \beta x_{t}+n_{t} $$ 
$$n_{t}=\mu+\alpha_1y_{t-1}+\alpha_2y_{t-2} + ...+\alpha_py_{t-p}\\-\theta_1\varepsilon_{t-1}-\theta_2\varepsilon_{t-2}-...-\theta_p\varepsilon_{t-p}$$
其中，$\mu$是常数项，$\alpha_i$(1,2,...,p)和$\varepsilon_i$(1,2,...,p)为待估的参数，$\varepsilon_p$为方差为$\sigma^2$的白噪声过程，X是引入的解释变量，$\beta$为其待估的参数。

# **参考文献**
1. Huazhen Lin, et al. *Comparative Analysis of Early Dynamic Trends in Novel Coronavirus Outbreak: A Modeling Framework*. medRxiv 2020.02.21.20026468.  
2. Zaixing Shi,Ya Fang. *Temporal relationship between outbound traffic from Wuhan and the 2019 coronavirus disease (COVID-19) incidence in China*. medRxiv 2020.03.15.20034199.  
3. 杨华磊，吴远洋，蔺雪钰. 新冠状病毒肺炎、人口迁移与疫情扩散防控. 中国管理科学[J], 2020(03): 1-10.  
4. 廖可等. 人口迁入与新增确诊数的趋势关系及因果量化分析. 数学建模及其应用[J], 2020(01): 23-28.  
5. 陈田木等. 厦门市新型冠状病毒肺炎人群传播能力计算与防控措施效果的模拟评估. 厦门大学学报(自然科学版), 2020(03): 1-8.  