---
title: "A Data Science Lab Project Template in R Markdown"
author: 虞睿灵 董洁 常佳琪
date: "`r format(Sys.time(), '%d %B %Y')`"
documentclass: article
papersize: letter
fontsize: 11pt
bibliography: template.bib
biblio-style: asa
output:
  bookdown::pdf_document2
  bookdown::html_document2
abstract: |
   刚刚
---


```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
## some utility functions, see the source code for details
source("utils_template.R")
## specify the packages needed
pkgs <- c("DT", "leaflet", "splines2", "webshot")
need.packages(pkgs)
## external data can be read in by regular functions,
## such as read.table or load
## for latex and html output
isHtml <- knitr::is_html_output()
isLatex <- knitr::is_latex_output()
latex <- ifelse(isLatex, '\\LaTeX\\', 'LaTeX')
## specify global chunk options
knitr::opts_chunk$set(fig.width = 5, fig.height = 4, dpi = 300,
                      out.width = "90%", fig.align = "center")
```

# 引言

# 理论介绍

## 互相关分析

## ARIMAX

# 描述性统计分析

# 实证分析

## 互相关分析
```{r,eval=T,echo=FALSE,error=FALSE,message=FALSE}
data<-read.csv("./data/new_correlation.csv")
attach(data)
library(ggplot2)
library(ggpubr)
library(rstatix)
library(ggpmisc)
theme_set(ggpubr::theme_pubr()+
            theme(legend.position = "top"))
library(ggpubr)
p1<- ggscatter(data, x = "mig", y = "distance",color = "black",
          add = "reg.line",conf.int = TRUE,    
          add.params = list(fill = "lightgray")
)+
  stat_cor(method = "pearson", 
           label.x = 3, label.y = 30)
p2<- ggscatter(data, x = "mig", y = "train",color = "black",
          add = "reg.line",conf.int = TRUE,    
          add.params = list(fill = "lightgray")
)+
  stat_cor(method = "pearson", 
           label.x = 3, label.y = 30)
p3<- ggscatter(data, x = "mig", y = "GDP",color = "black",
          add = "reg.line",conf.int = TRUE,    
          add.params = list(fill = "lightgray")
)+
  stat_cor(method = "pearson", 
           label.x = 3, label.y = 30)
p4<- ggscatter(data, x = "mig", y = "population",color = "black",
          add = "reg.line",conf.int = TRUE,    
          add.params = list(fill = "lightgray")
)+
  stat_cor(method = "pearson", 
           label.x = 3, label.y = 30)
ggarrange(p1,p2,p3,p4,ncol=2,nrow=2,labels=c("A","B","C","D"))
```

## 格兰杰因果关系检验

|  原假设   |  P值 | 检验结果   |
|:----------:|:--------:|:----------:|
|case does not Granger Cause mig|0.9807|不拒绝|
|mig does not Granger Cause case|0.0184|拒绝|

## 互相关分析

## ARIMAX

# 结论与展望